_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.timm_model.Timm
  input_size: 3072
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10
  model: resnet18
